// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly ai: ai.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly colleges: colleges.ServiceClient
    public readonly db: db.ServiceClient
    public readonly events: events.ServiceClient
    public readonly dataexport: dataexport.ServiceClient
    public readonly groups: groups.ServiceClient
    public readonly materials: materials.ServiceClient
    public readonly notes: notes.ServiceClient
    public readonly notifications: notifications.ServiceClient
    public readonly reflections: reflections.ServiceClient
    public readonly tasks: tasks.ServiceClient
    public readonly timer: timer.ServiceClient
    public readonly upload: upload.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.ai = new ai.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.colleges = new colleges.ServiceClient(base)
        this.db = new db.ServiceClient(base)
        this.events = new events.ServiceClient(base)
        this.dataexport = new dataexport.ServiceClient(base)
        this.groups = new groups.ServiceClient(base)
        this.materials = new materials.ServiceClient(base)
        this.notes = new notes.ServiceClient(base)
        this.notifications = new notifications.ServiceClient(base)
        this.reflections = new reflections.ServiceClient(base)
        this.tasks = new tasks.ServiceClient(base)
        this.timer = new timer.ServiceClient(base)
        this.upload = new upload.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { generateInsights as api_ai_insights_generateInsights } from "~backend/ai/insights";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.generateInsights = this.generateInsights.bind(this)
        }

        /**
         * Generates AI insights using Google Gemini with caching.
         */
        public async generateInsights(params: RequestType<typeof api_ai_insights_generateInsights>): Promise<ResponseType<typeof api_ai_insights_generateInsights>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/insights`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_insights_generateInsights>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getUserInfo as api_auth_user_getUserInfo } from "~backend/auth/user";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getUserInfo = this.getUserInfo.bind(this)
        }

        /**
         * Retrieves the current user's information.
         */
        public async getUserInfo(): Promise<ResponseType<typeof api_auth_user_getUserInfo>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_user_getUserInfo>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { calculateAdmissionChance as api_colleges_admission_chance_calculateAdmissionChance } from "~backend/colleges/admission_chance";
import { create as api_colleges_create_create } from "~backend/colleges/create";
import { search as api_colleges_search_search } from "~backend/colleges/search";

export namespace colleges {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.calculateAdmissionChance = this.calculateAdmissionChance.bind(this)
            this.create = this.create.bind(this)
            this.search = this.search.bind(this)
        }

        /**
         * Calculates admission chance for a college based on student stats with optimized query.
         */
        public async calculateAdmissionChance(params: RequestType<typeof api_colleges_admission_chance_calculateAdmissionChance>): Promise<ResponseType<typeof api_colleges_admission_chance_calculateAdmissionChance>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/colleges/admission-chance`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_colleges_admission_chance_calculateAdmissionChance>
        }

        /**
         * Creates a new college entry.
         */
        public async create(params: RequestType<typeof api_colleges_create_create>): Promise<ResponseType<typeof api_colleges_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/colleges`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_colleges_create_create>
        }

        /**
         * Searches for colleges by name with optimized query and caching.
         */
        public async search(params: RequestType<typeof api_colleges_search_search>): Promise<ResponseType<typeof api_colleges_search_search>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
                query: params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/colleges/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_colleges_search_search>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    health as api_db_health_health,
    info as api_db_health_info
} from "~backend/db/health";

export namespace db {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.health = this.health.bind(this)
            this.info = this.info.bind(this)
        }

        /**
         * Health check endpoint for database connectivity
         */
        public async health(): Promise<ResponseType<typeof api_db_health_health>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/db/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_db_health_health>
        }

        /**
         * Database introspection endpoint for debugging
         */
        public async info(): Promise<ResponseType<typeof api_db_health_info>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/db/info`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_db_health_info>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_events_create_create } from "~backend/events/create";
import { deleteEvent as api_events_delete_deleteEvent } from "~backend/events/delete";
import { list as api_events_list_list } from "~backend/events/list";
import { update as api_events_update_update } from "~backend/events/update";

export namespace events {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteEvent = this.deleteEvent.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new event.
         */
        public async create(params: RequestType<typeof api_events_create_create>): Promise<ResponseType<typeof api_events_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_create_create>
        }

        /**
         * Deletes an event.
         */
        public async deleteEvent(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/events/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all events for the current user with optimized query and pagination.
         */
        public async list(params: RequestType<typeof api_events_list_list>): Promise<ResponseType<typeof api_events_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:  params.category,
                endDate:   params.endDate,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                page:      params.page === undefined ? undefined : String(params.page),
                startDate: params.startDate,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_list_list>
        }

        /**
         * Updates an existing event.
         */
        public async update(params: RequestType<typeof api_events_update_update>): Promise<ResponseType<typeof api_events_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                category:    params.category,
                date:        params.date,
                description: params.description,
                location:    params.location,
                title:       params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createExport as api_dataexport_data_createExport,
    listExports as api_dataexport_data_listExports
} from "~backend/export/data";

export namespace dataexport {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createExport = this.createExport.bind(this)
            this.listExports = this.listExports.bind(this)
        }

        /**
         * Creates a new data export request.
         */
        public async createExport(params: RequestType<typeof api_dataexport_data_createExport>): Promise<ResponseType<typeof api_dataexport_data_createExport>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/export/create`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dataexport_data_createExport>
        }

        /**
         * Lists all exports for the current user.
         */
        public async listExports(): Promise<ResponseType<typeof api_dataexport_data_listExports>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/export/list`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_dataexport_data_listExports>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_groups_create_create } from "~backend/groups/create";
import { join as api_groups_join_join } from "~backend/groups/join";
import { list as api_groups_list_list } from "~backend/groups/list";

export namespace groups {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.join = this.join.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Creates a new study group.
         */
        public async create(params: RequestType<typeof api_groups_create_create>): Promise<ResponseType<typeof api_groups_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/groups`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_groups_create_create>
        }

        /**
         * Joins a study group using a join code.
         */
        public async join(params: RequestType<typeof api_groups_join_join>): Promise<ResponseType<typeof api_groups_join_join>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/groups/join`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_groups_join_join>
        }

        /**
         * Lists study groups.
         */
        public async list(params: RequestType<typeof api_groups_list_list>): Promise<ResponseType<typeof api_groups_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:    params.limit === undefined ? undefined : String(params.limit),
                myGroups: params.myGroups === undefined ? undefined : String(params.myGroups),
                page:     params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/groups`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_groups_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_materials_create_create } from "~backend/materials/create";
import { deleteMaterial as api_materials_delete_deleteMaterial } from "~backend/materials/delete";
import { list as api_materials_list_list } from "~backend/materials/list";
import { update as api_materials_update_update } from "~backend/materials/update";

export namespace materials {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteMaterial = this.deleteMaterial.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new study material.
         */
        public async create(params: RequestType<typeof api_materials_create_create>): Promise<ResponseType<typeof api_materials_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/materials`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_materials_create_create>
        }

        /**
         * Deletes a study material.
         */
        public async deleteMaterial(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/materials/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all study materials for the current user with optimized query.
         */
        public async list(params: RequestType<typeof api_materials_list_list>): Promise<ResponseType<typeof api_materials_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:   params.limit === undefined ? undefined : String(params.limit),
                page:    params.page === undefined ? undefined : String(params.page),
                subject: params.subject,
                type:    params.type,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/materials`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_materials_list_list>
        }

        /**
         * Updates an existing material.
         */
        public async update(params: RequestType<typeof api_materials_update_update>): Promise<ResponseType<typeof api_materials_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                fileName: params.fileName,
                fileSize: params.fileSize,
                fileUrl:  params.fileUrl,
                mimeType: params.mimeType,
                subject:  params.subject,
                title:    params.title,
                type:     params.type,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/materials/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_materials_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_notes_create_create } from "~backend/notes/create";
import { deleteNote as api_notes_delete_deleteNote } from "~backend/notes/delete";
import { list as api_notes_list_list } from "~backend/notes/list";
import { update as api_notes_update_update } from "~backend/notes/update";

export namespace notes {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteNote = this.deleteNote.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new note.
         */
        public async create(params: RequestType<typeof api_notes_create_create>): Promise<ResponseType<typeof api_notes_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_create_create>
        }

        /**
         * Deletes a note.
         */
        public async deleteNote(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/notes/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all notes for the current user with optimized query and search.
         */
        public async list(params: RequestType<typeof api_notes_list_list>): Promise<ResponseType<typeof api_notes_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                page:   params.page === undefined ? undefined : String(params.page),
                search: params.search,
                tags:   params.tags,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_list_list>
        }

        /**
         * Updates an existing note.
         */
        public async update(params: RequestType<typeof api_notes_update_update>): Promise<ResponseType<typeof api_notes_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                color:   params.color,
                content: params.content,
                tags:    params.tags,
                title:   params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notes/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notes_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_notifications_create_create } from "~backend/notifications/create";
import { list as api_notifications_list_list } from "~backend/notifications/list";
import { markRead as api_notifications_mark_read_markRead } from "~backend/notifications/mark_read";

export namespace notifications {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.markAllRead = this.markAllRead.bind(this)
            this.markRead = this.markRead.bind(this)
        }

        /**
         * Creates a new notification.
         */
        public async create(params: RequestType<typeof api_notifications_create_create>): Promise<ResponseType<typeof api_notifications_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_create_create>
        }

        /**
         * Retrieves all notifications for the current user.
         */
        public async list(params: RequestType<typeof api_notifications_list_list>): Promise<ResponseType<typeof api_notifications_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:      params.limit === undefined ? undefined : String(params.limit),
                page:       params.page === undefined ? undefined : String(params.page),
                unreadOnly: params.unreadOnly === undefined ? undefined : String(params.unreadOnly),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_list_list>
        }

        /**
         * Marks all notifications as read.
         */
        public async markAllRead(): Promise<void> {
            await this.baseClient.callTypedAPI(`/notifications/mark-all-read`, {method: "PUT", body: undefined})
        }

        /**
         * Marks a notification as read.
         */
        public async markRead(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/notifications/${encodeURIComponent(params.id)}/read`, {method: "PUT", body: undefined})
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_reflections_create_create } from "~backend/reflections/create";
import { list as api_reflections_list_list } from "~backend/reflections/list";
import { getStats as api_reflections_stats_getStats } from "~backend/reflections/stats";

export namespace reflections {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.getStats = this.getStats.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Creates or updates a reflection for a specific date.
         */
        public async create(params: RequestType<typeof api_reflections_create_create>): Promise<ResponseType<typeof api_reflections_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reflections`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reflections_create_create>
        }

        /**
         * Retrieves study statistics for the current user with optimized query.
         */
        public async getStats(): Promise<ResponseType<typeof api_reflections_stats_getStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reflections/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reflections_stats_getStats>
        }

        /**
         * Retrieves all reflections for the current user with optimized query.
         */
        public async list(params: RequestType<typeof api_reflections_list_list>): Promise<ResponseType<typeof api_reflections_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                endDate:   params.endDate,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                page:      params.page === undefined ? undefined : String(params.page),
                startDate: params.startDate,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reflections`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reflections_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_tasks_create_create } from "~backend/tasks/create";
import { deleteTask as api_tasks_delete_deleteTask } from "~backend/tasks/delete";
import { list as api_tasks_list_list } from "~backend/tasks/list";
import { update as api_tasks_update_update } from "~backend/tasks/update";

export namespace tasks {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteTask = this.deleteTask.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new task.
         */
        public async create(params: RequestType<typeof api_tasks_create_create>): Promise<ResponseType<typeof api_tasks_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tasks`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_create_create>
        }

        /**
         * Deletes a task.
         */
        public async deleteTask(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/tasks/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all tasks for the current user with optimized query and pagination.
         */
        public async list(params: RequestType<typeof api_tasks_list_list>): Promise<ResponseType<typeof api_tasks_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:    params.limit === undefined ? undefined : String(params.limit),
                page:     params.page === undefined ? undefined : String(params.page),
                priority: params.priority,
                status:   params.status,
                subject:  params.subject,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tasks`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_list_list>
        }

        /**
         * Updates an existing task.
         */
        public async update(params: RequestType<typeof api_tasks_update_update>): Promise<ResponseType<typeof api_tasks_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                dueDate:     params.dueDate,
                priority:    params.priority,
                startDate:   params.startDate,
                status:      params.status,
                subject:     params.subject,
                title:       params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tasks/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tasks_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { estimateTime as api_timer_estimate_estimateTime } from "~backend/timer/estimate";
import {
    createSession as api_timer_session_createSession,
    updateSession as api_timer_session_updateSession
} from "~backend/timer/session";

export namespace timer {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createSession = this.createSession.bind(this)
            this.estimateTime = this.estimateTime.bind(this)
            this.updateSession = this.updateSession.bind(this)
        }

        /**
         * Creates a new timer session.
         */
        public async createSession(params: RequestType<typeof api_timer_session_createSession>): Promise<ResponseType<typeof api_timer_session_createSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/timer/sessions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_timer_session_createSession>
        }

        /**
         * Estimates task completion time using AI.
         */
        public async estimateTime(params: RequestType<typeof api_timer_estimate_estimateTime>): Promise<ResponseType<typeof api_timer_estimate_estimateTime>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/timer/estimate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_timer_estimate_estimateTime>
        }

        /**
         * Updates a timer session with actual time.
         */
        public async updateSession(params: RequestType<typeof api_timer_session_updateSession>): Promise<ResponseType<typeof api_timer_session_updateSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/timer/sessions`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_timer_session_updateSession>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    deleteFile as api_upload_files_deleteFile,
    generateUploadUrl as api_upload_files_generateUploadUrl,
    getDownloadUrl as api_upload_files_getDownloadUrl
} from "~backend/upload/files";

export namespace upload {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteFile = this.deleteFile.bind(this)
            this.generateUploadUrl = this.generateUploadUrl.bind(this)
            this.getDownloadUrl = this.getDownloadUrl.bind(this)
        }

        /**
         * Deletes a file from storage.
         */
        public async deleteFile(params: RequestType<typeof api_upload_files_deleteFile>): Promise<void> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                fileKey: params.fileKey,
            })

            await this.baseClient.callTypedAPI(`/upload/files`, {query, method: "DELETE", body: undefined})
        }

        /**
         * Generates a signed upload URL for file uploads.
         */
        public async generateUploadUrl(params: RequestType<typeof api_upload_files_generateUploadUrl>): Promise<ResponseType<typeof api_upload_files_generateUploadUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/upload/generate-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_upload_files_generateUploadUrl>
        }

        /**
         * Gets a download URL for an existing file.
         */
        public async getDownloadUrl(params: RequestType<typeof api_upload_files_getDownloadUrl>): Promise<ResponseType<typeof api_upload_files_getDownloadUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/upload/download-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_upload_files_getDownloadUrl>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
